openapi: 3.0.3
info:
  title: Notes Application API
  version: 1.0.0
servers:
  - url: localhost:8080
tags:
  - name: Notes
    description: Everything is about your Notes

paths:
  /note/allNotes:
    get:
      tags:
        - Notes
      summary: Get all notes
      operationId: getAllNotes
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'

  /note/{id}:
    put:
      tags:
        - Notes
      summary: Update a Note by id
      operationId: updateNoteById
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteRequest'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Unique Id for note
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    delete:
      tags:
        - Notes
      summary: Delete a Note by id
      operationId: deleteNoteById
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Unique Id for note
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    get:
      tags:
        - Notes
      summary : Get a Note by id
      operationId: getNoteById
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Unique Id for note
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
  /note:
    post:
      tags:
        - Notes
      summary: Create a new Note
      operationId: createNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
components:
  schemas:
    NoteRequest:
      required:
        - title
        - description
      type: object
      properties:
        title:
          type: string
          example: "India"
        description:
          type: string
          example: "India is a country."

    Note:
      type: object
      properties:
        id:
          type: string
          example: "d8eb7002-1204-40e2-a770-e628129ad4d0"
        title:
          type: string
          example: "India"
        description:
          type: string
          example: "India is a country."