openapi: 3.0.3
info:
  title: Notes Application API
  version: 1.0.0
servers:
  - url: localhost:8080
tags:
  - name: Notes
    description: Everything is about your Notes
paths:
  /note:
    post:
      tags:
        - Notes
      summary: Create a new Note
      operationId: createNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNoteRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateNoteResponse'
components:
  schemas:
    Note:
      required:
        - note
        - content
      type: object
      properties:
        note:
          type: string
          example: "India"
        content:
          type: string
          example: "India is a country."
    CreateNoteResponse:
      required:
        - id
        - note
        - content
      type: object
      properties:
        id:
          type: string
          example: "d8eb7002-1204-40e2-a770-e628129ad4d0"
        note:
          type: string
          example: "India"
        content:
          type: string
          example: "India is a country."
    CreateNoteRequest:
      required:
        - note
        - content
      type: object
      properties:
        note:
          type: string
          example: "India"
        content:
          type: string
          example: "India is a country."